### ISSUE TITLE
[question] a few questions / feature requests

### ISSUE THREAD

**Issue by florianlenz** [tiabc/doubleratchet#1]
Hi,

I have a few questions:

1. I would like to return errors from the key store since I currently have to drop the errors in order to satisfy the interface. Would you accept such an PR if I change the interface? 

2. Are message keys deleted at some point? I see that there is a `DeletePk` function however, it's only used to delete skipped keys as far as I can see. Since we have to safe all messages encrypted - we can just persist the messages keys and will be able to decrypt all messages from those keys at any point in time (or am I wrong)? 

cheers,
Florian

P.s. thanks for this great repo

**Comment by tiabc** [comment]
Hi, @florianlenz.

1. Yes, I think it's totally ok. What's more, the actual key store doesn't return errors just for the sake of simplicity.
2. Yes, correct. You can store the message keys and that's all required to decrypt a corresponding message.
